const songs = [
    {title: "Best of Soul Influence", link: "https://www.youtube.com/watch?v=1Cn3oBx6Fv0&list=RD1Cn3oBx6Fv0&start_radio=1&t=3598s"},
    {title: "Shuka", link:"https://www.youtube.com/watch?v=HxSdujjIy-c&list=RDHxSdujjIy-c&start_radio=1"},
    {title: "Without Love", link:"https://www.youtube.com/watch?v=-PEyaODURYY&list=RD-PEyaODURYY&start_radio=1"},
    {title: "In His Hands", link:"https://www.youtube.com/watch?v=ic_-YgizgtI&list=RDic_-YgizgtI&start_radio=1"},
    {title: "Ayerera", link:"https://www.youtube.com/watch?v=F9c8JauqQsI&list=RDF9c8JauqQsI&start_radio=1"},
    {title: "Alinisubiri", link:"https://www.youtube.com/watch?v=I1W3YcLGC8Y&list=RDI1W3YcLGC8Y&start_radio=1"},
    {title: "Tinga Malo", link:"https://www.youtube.com/watch?v=VvxAHARdtfE&list=RDVvxAHARdtfE&start_radio=1"},
    {title: "Amazing Grace Armor music", link:"https://www.youtube.com/watch?v=3KOZoPl1iGs&list=RD3KOZoPl1iGs&start_radio=1"},
    {title: "Dreaming of a City", link:"https://www.youtube.com/watch?v=djs_bLyzkRo&list=RDdjs_bLyzkRo&start_radio=1"},
    {title: "Gusa", link: "https://www.youtube.com/watch?v=f5OZKSneNvI&list=RDf5OZKSneNvI&start_radio=1"},
    {title: "Kivulini", link: "https://www.youtube.com/watch?v=5cKh0On4MKw&list=RD5cKh0On4MKw&start_radio=1"},
    {title:"Onge Ohala", link:"https://www.youtube.com/watch?v=fZ5q0a0Tj8k&list=RDfZ5q0a0Tj8k&start_radio=1"},
    {title: "Inuka Tena", link:"https://www.youtube.com/watch?v=nD2KzvwJGK0&list=RDnD2KzvwJGK0&start_radio=1"},
    {title: "Tulia", link:"https://www.youtube.com/watch?v=dJTLZCma7xI&list=RDdJTLZCma7xI&start_radio=1"},
    {title: "Kwetu Pazuri", link:"https://www.youtube.com/watch?v=WBd87TACLcE&list=RDWBd87TACLcE&start_radio=1"},
    {title: "Mbele Mbele", link:"https://www.youtube.com/watch?v=ZAQ2PfuITSU&list=RDZAQ2PfuITSU&start_radio=1"},
    {title: "Mtuliza Bahari", link:"https://www.youtube.com/watch?v=Eyog3BrJtfA&list=RDEyog3BrJtfA&start_radio=1"},
    {title: "Muda Hautoshi", link:"https://www.youtube.com/watch?v=iGgHl0LVIFo&list=RDiGgHl0LVIFo&start_radio=1"},
    {title: "Utakwenda", link:"https://www.youtube.com/watch?v=Ez7JD0Uku_A&list=RDEz7JD0Uku_A&start_radio=1"},
    {title: "Niraha", link:"https://www.youtube.com/watch?v=xeHmJXCkUjc&list=RDxeHmJXCkUjc&start_radio=1"},
    {title: "Tuonyeshe Yesu", link:"https://www.youtube.com/watch?v=lh7LtM0-hzY&list=RDlh7LtM0-hzY&start_radio=1"},
    {title: "Naimba", link:"https://www.youtube.com/watch?v=9fxpSFsFsBs&list=RD9fxpSFsFsBs&start_radio=1"},
    {title: "Mlinzi Wangu", link:"https://www.youtube.com/watch?v=fYWBoE-pziA&list=RDfYWBoE-pziA&start_radio=1"},
    {title: "Pahali Pema", link:"https://www.youtube.com/watch?v=nDfySBdTTiM&list=RDnDfySBdTTiM&start_radio=1"},
    {title: "Salama", link:"https://www.youtube.com/watch?v=mHcSybaOUQQ&list=RDmHcSybaOUQQ&start_radio=1"},
    {title: "Wimbo", link:"https://www.youtube.com/watch?v=scPFF7IYaoE&list=RDscPFF7IYaoE&start_radio=1"},
    {title: "Chukua Godoro", link:"https://www.youtube.com/watch?v=lo2GPbwnR3Q&list=RDlo2GPbwnR3Q&start_radio=1"},
    {title: "Nilikuwa nalo shamba", link:"https://www.youtube.com/watch?v=kEfj022qhaA&list=RDkEfj022qhaA&start_radio=1"},
    {title: "Radiance Acapella Unodei", link:"https://www.youtube.com/watch?v=V9G5q7TrE9Q&list=RDV9G5q7TrE9Q&start_radio=1"},
    {title: "Tumaini Sonda ya dihlu", link:"https://www.youtube.com/watch?v=QTTZIeVsTYM&list=RDQTTZIeVsTYM&start_radio=1"},
    {title: "Usifurahi juu yangu", link:"https://www.youtube.com/watch?v=sKOiyxQQUfo&list=RDsKOiyxQQUfo&start_radio=1"},
    {title: "Whispering Hope", link:"https://www.youtube.com/watch?v=Y9ey1mXIMqA&list=RDY9ey1mXIMqA&start_radio=1"},
    {title: "All we Ask, Shofar", link: "https://www.youtube.com/watch?v=pUpuU8vwHvw&list=RDpUpuU8vwHvw&start_radio=1"},
    {title: "Blessings", link:"https://www.youtube.com/watch?v=zRJHuBG2fqM&list=RDzRJHuBG2fqM&start_radio=1"},
    {title: "I could Sing About heaven", link:"https://www.youtube.com/watch?v=4hWs5nDEfEM&list=RD4hWs5nDEfEM&start_radio=1"},
    {title: "It's going far", link:"https://www.youtube.com/watch?v=IeKbRptdeic&list=RDIeKbRptdeic&start_radio=1"},
    {title: "Redeemed, Stand Music", link:"https://www.youtube.com/watch?v=cqc6iozTiVI&list=RDcqc6iozTiVI&start_radio=1"},
    {title: "Upendo, Pillars of Faith", link:"https://www.youtube.com/watch?v=_6DzQCHj9us&list=RD_6DzQCHj9us&start_radio=1"},
    {title: "Sifa Kwa Bwana", link:"https://www.youtube.com/watch?v=0SeJJ4fk_ss&list=RD0SeJJ4fk_ss&start_radio=1"},
    {title: "Maombi", link:"https://www.youtube.com/watch?v=0IXjvc9ntaw&list=RD0IXjvc9ntaw&start_radio=1"},
    {title: "Zamu ya Huduma", link:"https://www.youtube.com/watch?v=wE9CD0IoATY&list=RDwE9CD0IoATY&start_radio=1"},
    {title: "Vitu vidogo", link: "https://www.youtube.com/watch?v=eK1ooCUPNiA&list=RDeK1ooCUPNiA&start_radio=1"},
    {title: "Waliketi Chini", link: "https://www.youtube.com/watch?v=K7ftATkickM&list=RDK7ftATkickM&start_radio=1"},
    {title: "Petero", link:"https://www.youtube.com/watch?v=dxNZOpmz8cg&list=RDdxNZOpmz8cg&start_radio=1"},
    {title: "Japo ni machungu", link:"https://www.youtube.com/watch?v=Hmv1SxO6V1Q&list=RDHmv1SxO6V1Q&start_radio=1"},
    {title: "Mungu si binadamu", link:"https://www.youtube.com/watch?v=GHnKZuxGVxU&list=RDGHnKZuxGVxU&start_radio=1"},
    {title: "Kisha Nikaona", link: "https://www.youtube.com/watch?v=UkmHmTsaEao&list=RDUkmHmTsaEao&start_radio=1"},
    {title: "Chukua Udongo tena", link: "https://www.youtube.com/watch?v=X0kJTD6bieU&list=RDX0kJTD6bieU&start_radio=1"},
    {title: "Burudika", link:"https://www.youtube.com/watch?v=IlZSPji_A2I&list=RDIlZSPji_A2I&start_radio=1"},
    {title: "Mbilikimo", link:"https://www.youtube.com/watch?v=Vi9ga19CAp0&list=RDVi9ga19CAp0&start_radio=1"},
    {title: "Sitaki Kujua, Kurasini", link: "https://www.youtube.com/watch?v=tXUMD_CX5II&list=RDtXUMD_CX5II&index=1"},
    {title: "Galilaya", link:"https://www.youtube.com/watch?v=RLCqu6GwN7o&list=RDtXUMD_CX5II&index=3"},
    {title: "Majitu Marefu", link:"https://www.youtube.com/watch?v=7ojC2Vrs-Z4&list=RDtXUMD_CX5II&index=5"},
    {title: "Tungamira", link: "https://www.youtube.com/watch?v=EuhNX7tGXxs&list=RDtXUMD_CX5II&index=7"},
    {title: "Nahodha", link:"https://www.youtube.com/watch?v=gJECs4zlG5s&list=RDtXUMD_CX5II&index=11"},
    {title: "The Brooklyn Tabernacle Choir", link:"https://www.youtube.com/watch?v=DfW2mkkMTAg&list=RDDfW2mkkMTAg&start_radio=1"},
    {title: "The promise", link:"https://www.youtube.com/watch?v=jeiPSHEd2Zc&list=RDjeiPSHEd2Zc&start_radio=1"},
    {title: "Four days late", link:"https://www.youtube.com/watch?v=se7yAkqu3Ek&list=RDse7yAkqu3Ek&start_radio=1"},
    {title: "Onge Yawa", link:"https://www.youtube.com/watch?v=WFUMPMv1e88&list=RDWFUMPMv1e88&start_radio=1"}
]